name: PR Semantics
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review
      - review_requested

jobs:
  main:
    name: Validate title semantics
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
